<?php

namespace Tests\Unit;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ServerTest extends TestCase
{
    /**
     * Tests the application's main page returns a successful response
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    /**
     * Tests the laravel autogenerated docs returns a successful response
     */
    public function test_the_request_docs_returns_a_successful_response(): void
    {
        $response = $this->get('/request-docs/api?openapi=true');

        $response->assertStatus(200);
    }
}
